name: Composite Action
description: "My custom Action"
inputs:
  working-dir:
    description: "a"
    default: "."
  node-version:
    description: "b"
    default: "."

runs:
  using: composite
  defaults:
    shell: bash

  runs-on: ubuntu-latest
  working-directory: ${{ inputs.working-dir }}
  steps:
    - name: Setup Node
      shell: bash
      uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run Unit Tests
      run: npm run test